filelists:
  __default:
    - 'etc-astute.yaml'
    - 'etc-default'
    - 'etc-mcollective'
    - 'etc-resolv.conf'
    - 'root-anaconda'
    - 'root-.ks'
    - 'root-.log'
    - 'var-lib-cloud'
    - 'var-lib-puppet-state-last_run_summary.yaml'
    - 'var-run-pcap_dir'
  by_roles:
    fuel:
      - 'etc-astute'
      - 'etc-centos-release'
      - 'etc-cobbler'
      - 'etc-dnsmasq.conf'
      - 'etc-fuel'
      - 'etc-nailgun'
    controller:
      - 'etc-apache2'
      - 'etc-ceph'
      - 'etc-cinder'
      - 'etc-glance'
      - 'etc-haproxy'
      - 'etc-heat'
      - 'etc-keystone'
      - 'etc-mysql'
      - 'etc-nova'
      - 'etc-swift'
      - 'root-ceph'
    cinder: ['etc-cinder']
    cinder-block-device: ['etc-cinder']
    ceph-osd: ['root-ceph', 'etc-ceph']
    compute: ['etc-libvirt', 'etc-nova']
    ironic: ['etc-ironic']
    no_fuel: ['etc-hiera', 'etc-neutron']
    virt: ['etc-libvirt']
  by_os_platform:
    ubuntu: ['etc-apt', 'etc-lsb-release', 'etc-network']
    centos: ['etc-redhat-release', 'etc-sysconfig', 'etc-yum']
  by_release:
    '9.0': ['etc-fuel']
    '9.1': ['etc-fuel']
scripts:
  by_release:
    '4.1':
      by_roles:
        controller: [nova-manage-vm-list]
    '4.1.1':
      by_roles:
        controller: [nova-manage-vm-list]
    '5.0':
      by_roles:
        fuel: [fuel-docker-ps, fuel-dockerctl-check]
        controller: [nova-manage-vm-list]
    '5.0.1':
      by_roles:
        fuel: [fuel-docker-ps, fuel-dockerctl-check]
        controller: [nova-manage-vm-list]
    '5.1':
      by_roles:
        fuel: [fuel-dockerctl-list, fuel-docker-ps, fuel-dockerctl-check]
        controller: [nova-manage-vm-list]
    '5.1.1':
      by_roles:
        fuel: [fuel-dockerctl-list, fuel-docker-ps, fuel-dockerctl-check]
        controller: [nova-manage-vm-list]
    '6.0':
      by_roles:
        fuel: [fuel-dockerctl-list, fuel-docker-ps, fuel-dockerctl-check, docker-images]
        compute: [ipset-save, ipset-list]
        controller: [ipset-save, ipset-list, nova-manage-vm-list]
    '6.1':
      by_roles:
        fuel: [fuel-notifications, fuel-dockerctl-list, fuel-docker-ps, fuel-dockerctl-check, docker-images]
        controller: [nova-manage-vm-list]
    '7.0':
      by_roles:
        fuel: [fuel-notifications, fuel-dockerctl-list, fuel-docker-ps, fuel-dockerctl-check, docker-images, fuel-all-network-templates-combined-yaml]
    '8.0':
      by_roles:
        fuel: [fuel-notifications, fuel-dockerctl-list, fuel-docker-ps, fuel-dockerctl-check, docker-images, fuel-bootstrap-list, fuel-all-network-templates-combined-yaml]
    '9.0':
      by_roles:
        fuel: [fuel-notifications, fuel-bootstrap-list, shotgun2-report, fuel-all-network-templates-combined-yaml]
  by_roles:
    fuel: [fuel-release, fuel-task-list, fuel-environment-list, fuel-postgres-dump, fuel-node-json]
    cinder: [ovs-vsctl-show, cinder-manage]
    compute: [ovs-dump-flows, ovs-ofctl-show-bridges, ovs-vsctl-show]
    controller: [rabbitmqctl-list-queues, nova-service-list,
      rabbitmqctl-cluster-status, crm-resource-status, pcs-status, ovs-dump-flows, neutron-agent-list,
      mysql-status, ceph-mon-status, ovs-ofctl-show-bridges, rabbitmqctl-list-connections,
      ovs-vsctl-show, rabbitmqctl-report, mysql-size, rabbitmqctl-status, crm-resource-list,
      cinder-manage, haproxy-stats-html, haproxy-stats-show-info, haproxy-stats-show-stat, haproxy-stats-show-errors, haproxy-stats-show-sess]
    mongo: [mongo-replication-status, ipa, mongo-replica-conf, mongo-status, ovs-vsctl-show]
  once_by_roles:
    ceph-osd: [ceph-df, ceph-osd-status, ceph-osd-tree, ceph-pg-dump, ovs-vsctl-show,
      ceph-health-detail, ceph-health]
    controller: [neutron-router-list, neutron-net-list, neutron-subnet-list, keystone-endpoint-list,
      cinder-list, nova-list, keystone-tenant-list, nova-usage-list,
      neutron-port-list]
  by_os_platform:
      ubuntu: [dmesg-t-ubuntu, dpkg-l, apt-cache-policy]
      centos: [dmesg-centos, yum-list-installed, yum-v-repolist]
  __default:
    [ip-ne, iptables-nvL, iptables-save, iptables-namespaces-nvL, iptables-namespaces-save, ipnetns, ss, ipa, df-m, services-status, cpuinfo, df-i, ipro, mount, sysctl-a, pvdisplay, vgdisplay, lvdisplay, lsmod, dmidecode, cat-proc-interrupts, arp-an, uname-a, ps-auxwwf, uptime, dmsetup-info, brctl-show, blkid-o-list]
logs:
  __default:
    path: '/var/log'
#    exclude:
#      - '\.[^12]\.gz$|\.\d{2,}\.gz$'
# cmds:
#   __default:
#     test:
#       'echo "test" | head -n 1'
#     test2:
#       'echo "test2" | less'
#   by_roles:
#     compute:
#       t3: 'echo t3'
#       t4: 'echo t4'
