#!/bin/bash
exec /usr/bin/env python - << EOF
#!/usr/bin/env python2
# -*- coding: utf-8 -*-

from fuelclient.v1.environment import EnvironmentClient
import subprocess
import json
import yaml

class CEnvironmentClient(EnvironmentClient):
    def download_network_template(self, environment_id):
        env = self._entity_wrapper(environment_id)
        template_data = env.get_network_template_data()
        return template_data

ec = CEnvironmentClient()
p = subprocess.Popen(['fuel', 'env', 'list', '--json'],
                     stdout=subprocess.PIPE,
                     stderr=subprocess.PIPE)
out, err = p.communicate()
clusters_dict = json.loads(out)
for cluster in clusters_dict:
    clid=int(cluster['id'])
    print('---\n# cluster id:%s\n%s' %(clid, yaml.dump(yaml.load((json.dumps(ec.download_network_template(clid)))))))
EOF
